allowBuilds:
  esbuild: set this to true or false

saveExact: true
ignoreScripts: true
engineStrict: true
packageManagerStrict: true
minimumReleaseAge: 10080
minimumReleaseAgeStrict: true

packages:
  - .
  - app
  - packages/*
