/**
 * Generates site/src/data/modules.ts by reading the source directory.
 * Run with: npx tsx scripts/generate-site-data.ts
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { listModules, resolveDependencies } from "./copy-resolver.js";

const __dirname = join(fileURLToPath(import.meta.url), "..");
const SRC_DIR = resolve(__dirname, "..", "src");
const OUTPUT_FILE = resolve(__dirname, "..", "site", "src", "data", "modules.ts");

interface ModuleInfo {
  name: string;
  file: string;
  code: string;
  dependencies: string[];
  exports: string[];
}

function extractExports(code: string): string[] {
  const exports: string[] = [];
  // export function name
  const funcMatches = code.matchAll(/export\s+function\s+(\w+)/g);
  for (const m of funcMatches) {
    exports.push(m[1]!);
  }
  // export type Name
  const typeMatches = code.matchAll(/export\s+type\s+(\w+)/g);
  for (const m of typeMatches) {
    exports.push(m[1]!);
  }
  // export interface Name
  const interfaceMatches = code.matchAll(/export\s+interface\s+(\w+)/g);
  for (const m of interfaceMatches) {
    exports.push(m[1]!);
  }
  // export class Name
  const classMatches = code.matchAll(/export\s+class\s+(\w+)/g);
  for (const m of classMatches) {
    exports.push(m[1]!);
  }
  // export const name
  const constMatches = code.matchAll(/export\s+const\s+(\w+)/g);
  for (const m of constMatches) {
    exports.push(m[1]!);
  }
  return exports;
}

function generateModulesData(): string {
  const moduleNames = listModules(SRC_DIR);
  const modules: ModuleInfo[] = [];

  for (const name of moduleNames) {
    const deps = resolveDependencies(name, SRC_DIR);
    const filePath = join(SRC_DIR, `${name}.ts`);
    const code = readFileSync(filePath, "utf-8");
    const exports = extractExports(code);

    // Dependencies are other modules (not self)
    const depNames = deps
      .map((d) =>
        d
          .replace(SRC_DIR, "")
          .replace(/^[\\/]/, "")
          .replace(/\.tsx?$/, ""),
      )
      .filter((d) => d !== name);

    modules.push({ name, file: `${name}.ts`, code, dependencies: depNames, exports });
  }

  const json = JSON.stringify(modules, null, 2).replace(/`/g, "\\`").replace(/\$\{/g, "\\${");

  return `// Auto-generated by scripts/generate-site-data.ts — do not edit\nexport const modules = ${json} as const;\n`;
}

const content = generateModulesData();
writeFileSync(OUTPUT_FILE, content);
console.log(`Generated ${OUTPUT_FILE}`);
