// Auto-generated by scripts/generate-site-data.ts — do not edit
export const modules = [
  {
    name: "math",
    file: "math.ts",
    code: "/** Clamp a number between min and max. */\nexport function clamp(value: number, min: number, max: number): number {\n  return Math.min(Math.max(value, min), max);\n}\n\n/** Linear interpolation between a and b by t (0–1). */\nexport function lerp(a: number, b: number, t: number): number {\n  return a + (b - a) * clamp(t, 0, 1);\n}\n\n/** Map a value from one range to another. */\nexport function mapRange(value: number, inMin: number, inMax: number, outMin: number, outMax: number): number {\n  const t = (value - inMin) / (inMax - inMin);\n  return lerp(outMin, outMax, t);\n}\n",
    dependencies: [],
    exports: ["clamp", "lerp", "mapRange"],
  },
  {
    name: "string",
    file: "string.ts",
    code: 'import { clamp } from "./math.js";\n\n/** Capitalize the first letter of a string. */\nexport function capitalize(str: string): string {\n  if (str.length === 0) return str;\n  return str[0]!.toUpperCase() + str.slice(1);\n}\n\n/** Convert a string to kebab-case. */\nexport function toKebabCase(str: string): string {\n  return str\n    .replace(/([a-z])([A-Z])/g, "$1-$2")\n    .replace(/[\\s_]+/g, "-")\n    .toLowerCase();\n}\n\n/** Truncate a string to a maximum length, adding an ellipsis if needed. */\nexport function truncate(str: string, maxLen: number, suffix = "..."): string {\n  const effectiveLen = clamp(maxLen - suffix.length, 1, maxLen);\n  if (str.length <= maxLen) return str;\n  return str.slice(0, effectiveLen) + suffix;\n}\n',
    dependencies: ["math"],
    exports: ["capitalize", "toKebabCase", "truncate"],
  },
] as const;
